import { TestCase } from "../analyse-helper";

const valid: (RegExp | TestCase)[] = [
	/a+a+/,
	/Za*b*c*/,
	/#a*b+a*/,
	/^[\s\S]+(?=\/[a-z]+$)/,
	/^(?:a+){1}/,
	/^(?:a+)?/,
	/^(?:[^\s]|\s+(?!\s))(?=\s*a)/,

	/#.*/,

	// regexes generated by refa
	/^[ax](?:a*x)*(?:(?:y[az]|a(?:z|y[az]))[az]*|a{2,}(?:(?:z|y[az])[az]*)?)$/,
	/^(?:a*x)*(?:y[az]*|a+(?:[yz][az]*)?)$/,
];

export const cases: TestCase[] = valid.map(value => (value instanceof RegExp ? { literal: value } : value));
